spring:
  cloud: #配置读取配置 读取github(云)上的配置
    config:
      uri: http://localhost:8888
      name: itoken-zuul
      label: master
      profile: dev

#spring:
#  application:
#    name: itoken-zuul
#  zipkin: #zipkin 服务追踪依赖
#    base-url: http://localhost:9411
#  boot:  # spring boot admin 健康检查地址配置
#    admin:
#      client:
#        url: http://localhost:8084
#
#server:
#  port: 8769
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#
#zuul: #网关配置
#  routes: #路由
#    api-a: #自己起名
#      path: /api/a/**   # **全目录匹配
#      serviceId: hello-spring-cloud-web-admin-ribbon
#    api-b:
#      path: /api/b/**
#      serviceId: hello-spring-cloud-web-admin-feign